Completed Lesson_2
borisshavrin/geekshop pull request #3
Opened 2021-05-30 21:27 UTC by borisshavrin

2021-05-31 07:17 UTC, Vokler requested changes

2021-05-31 07:17 UTC, Vokler commented on products/views.py
> +def base(request):
А зачем вы создали контроллер для base? base.html - абстрактный шаблон, от которого просто наследуются index.html и products.html

2021-05-31 07:17 UTC, Vokler commented on products/fixtures/products_list.json
> +{
Вам нужно организовать здесь список из словарей, чтобы в шаблоне иттерироваться по этому списку и выводить информацию о товаров. Цикл for нужено, чтобы избежать повторения блоков с товарами.

2021-05-31 19:34 UTC, borisshavrin commented on products/fixtures/products_list.json
> +{
Организовал, но по сути ничего не поменялось) 
Я ведь верно делаю, что заношу в context пары (key = item_n, value = описание), после чего в products.html вызываю нужные параметры из context ? 
Сейчас сделаю коммит

2021-05-31 19:57 UTC, borisshavrin commented on products/views.py
>      return render(request, 'products/products.html', context)
@Vokler исключил base() контроллер

2021-05-31 19:57 UTC, borisshavrin commented on products/fixtures/products_list.json
> +  {
@Vokler здесь я как то коряво вставил список. В следующем коммите оформил более верный формат

2021-05-31 19:57 UTC, borisshavrin commented on products/fixtures/products_list.json
> +{
@Vokler вот сейчас должно быть ок

2021-06-01 06:34 UTC, Vokler commented on products/fixtures/products_list.json
> +{
Не совсем все-таки вы выерно организовывайте список из продуктов.
Должна быть следующая конструкция:
context = `{'title': '...', 'products': [{...}, {...}, {...}]}`.
Посмотрите урок внимательнее

2021-06-01 19:57 UTC, borisshavrin commented on products/fixtures/products_list.json
> +{
@Vokler Исправил, посмотрите пожалуйста.

2021-06-02 07:57 UTC, Vokler approved these changes

2021-06-02 07:57 UTC, merged